name: GitHub Metrics
on:
  # Schedule daily updates
  schedule:
    - cron: "0 0 * * *"  # Runs at 00:00 UTC every day
  # Allow manual trigger
  workflow_dispatch:
  # Run on push to update metrics
  push:
    branches:
      - main

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Generate Metrics
        uses: lowlighter/metrics@latest
        with:
          # GitHub token with necessary permissions
          token: ${{ secrets.METRICS_TOKEN }}
          
          # Options
          user: fizamusthafa
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: America/New_York
          
          # Output
          filename: github-metrics.svg
          
          # Plugin: Follow-up of issues and pull requests
          plugin_followup: yes
          plugin_followup_sections: repositories
          
          # Plugin: Activity
          plugin_activity: yes
          plugin_activity_days: 14
          plugin_activity_filter: all
          plugin_activity_limit: 5
          plugin_activity_load: 300
          plugin_activity_visibility: all
          
          # Plugin: Achievements
          plugin_achievements: yes
          plugin_achievements_display: compact
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: C
          
          # Plugin: Notable contributions
          plugin_notable: yes
          plugin_notable_from: organization
          plugin_notable_repositories: yes
          
          # Plugin: Languages
          plugin_languages: yes
          plugin_languages_analysis_timeout: 15
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages_limit: 8
          plugin_languages_recent_categories: markup, programming
          plugin_languages_recent_days: 14
          plugin_languages_recent_load: 300
          plugin_languages_sections: most-used
          plugin_languages_threshold: 0%
          
          # Plugin: Lines of code changed
          plugin_lines: yes
          
          # Plugin: Habits (Contributions breakdown)
          plugin_habits: yes
          plugin_habits_days: 14
          plugin_habits_facts: yes
          plugin_habits_charts: yes
          plugin_habits_trim: yes
